apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guri-postgres
spec:
  project: default
  source:
    repoURL: https://github.com/amserdion01/newargo.git
    targetRevision: main
    path: postgres
  destination:
    server: https://kubernetes.default.svc
    namespace: guri
  syncPolicy: 
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true